"""Initial migration

Revision ID: 70ad800a64be
Revises: 
Create Date: 2025-05-28 19:55:58.915491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70ad800a64be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    op.drop_table('appointments')
    op.drop_table('password_resets')
    op.drop_table('messages')
    op.drop_table('assignments')
    op.drop_table('recordings')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'psychologist', 'patient'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('admin', 'psychologist', 'patient'),
               existing_nullable=False)

    op.create_table('recordings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('appointment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('recordings_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('assignments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('psychologist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name=op.f('assignments_ibfk_2')),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], name=op.f('assignments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('conversation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('sent_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_ibfk_1')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('messages_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('password_resets',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('password_resets_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('psychologist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('datetime', mysql.DATETIME(), nullable=False),
    sa.Column('duration', mysql.INTEGER(display_width=11), server_default=sa.text('60'), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('scheduled', 'completed', 'cancelled'), server_default=sa.text("'scheduled'"), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name=op.f('appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], name=op.f('appointments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conversations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('psychologist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name=op.f('conversations_ibfk_2')),
    sa.ForeignKeyConstraint(['psychologist_id'], ['user.id'], name=op.f('conversations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
